<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.29/browser.js"></script>
	<script type="text/babel">
	//Promise 对象用于表示一个异步操作的最终状态（完成或失败），以及其返回的值。
	//Promise的构造函数接收一个参数，是函数，并且传入两个参数：resolve，reject，分别表示异步操作执行成功后的回调函数和异步操作执行失败后的回调函数。	
	
	// demo 1
	// const delay = seconds => {
	// 	return new Promise(resolve => {
	// 		setTimeout(resolve,seconds * 1000)
	// 	});
	// };
	// console.log("start");
	// delay(1).then(() => console.log("one second"));
	// delay(2).then(() => console.log("two second"));
	// delay(3).then(() => console.log("three second"));
	// delay(3).then(() => console.log("three2 second"));
 
	// demo 2

	const delay2 = seconds => {
		return new Promise((resolve,reject) => {
			if(typeof seconds !== 'number'){
				// reject(new Error("Argument seconds should be a number~!"))
				reject("Argument seconds should be a number~!");
			}
			setTimeout(
				() => resolve(`${seconds} second delay is up`),
				seconds * 1000
			);
		});
	};

	delay2(1).then(msg => msg.toUpperCase())
			 .then(msg => `${msg}~~~!!!!`)
			 .then(msg => console.log(msg)) 
			 .finally(console.log('finally~ delay 1 second!'));

	delay2("10 Minuts").catch(msg => console.log('catch:' + msg))
			 .finally(msg => console.log('finally~!'));
 
	// Promise.reject("Testing static reject").then(function(reason) {
	//   // 未被调用 
	// }, function(reason) {
	// 	console.log( reason); // "Testing static reject"
	// });

	Promise.reject(new Error("fail")).then(function(result) {
	// 未被调用
	}, function(error) {
		console.log("Error:"+ error); // stacktrace
	});

	</script>
	<title>Promises</title>
</head>
<body>
</body>	
</html>






